plugins {
    id 'eclipse'
    id 'idea'
    id 'net.minecraftforge.gradle' version "${forge_gradle_version}"
    id 'org.spongepowered.mixin' version "${mixin_gradle_version}"
    id 'com.gradleup.shadow' version "${shadow_version}"
}

version = mod_stage != "" ? "${mc_version}-${mod_version}-${mod_stage}" : "${mc_version}-${mod_version}"
group = mod_group
base.archivesName = mod_name

java.toolchain.languageVersion = JavaLanguageVersion.of(8)

minecraft {
    mappings channel: "${mappings_channel}", version: "${mappings_version}"

    runs {
        client {
            taskName "runClient ${mod_name} ${mc_version}"
            environment 'MC_VERSION', "${mc_version}"
            property 'fml.coreMods.load', "${dependency_plugin_classes},${mod_plugin_class}"
        }

        server {
            taskName "runServer ${mod_name} ${mc_version}"
            environment 'MC_VERSION', "${mc_version}"
            property 'fml.coreMods.load', "${dependency_plugin_classes},${mod_plugin_class}"
        }
    }
}

configurations {
    bundled
    implementation.extendsFrom(bundled)
}

dependencies {
    minecraft "net.minecraftforge:forge:${mc_version}-${forge_version}"
    shadow "org.spongepowered:mixin:${mixin_version}"

    bundled 'io.github.meldexun:asmutil:2.8.1'
    bundled 'io.github.meldexun:memoryutil:1.1.0'
    bundled 'io.github.meldexun:matrixutil:1.5.0'

    shadow fg.deobf('io.github.meldexun:betterconfig:1.12.2-1.2.0:thin')
}

processResources {
    inputs.property('version', mod_stage != "" ? "${mod_version}-${mod_stage}" : "${mod_version}")

    filesMatching('mcmod.info') {
        expand version: inputs.properties.get('version')
    }
}

java {
    withSourcesJar()
}

jar {
    archiveBaseName = mod_name
    archiveAppendix = mc_version
    archiveVersion = mod_version
    archiveClassifier = mod_stage != "" ? mod_stage + '-thin' : 'thin'

    manifest {
        attributes 'ModSide': 'CLIENT'
        attributes 'FMLCorePlugin': "${mod_plugin_class}"
    }
}

jar.finalizedBy('reobfJar')

shadowJar {
    archiveClassifier = ''

    configurations = [project.configurations.bundled]
}

reobf {
    shadowJar {}
}

shadowJar.finalizedBy('reobfShadowJar')
